name: Run Postman Tests and Deploy to GitHub Pages

on:
  workflow_dispatch:  # manual trigger
  schedule:
    - cron: '0 0 * * *'  # daily at midnight

jobs:
  run-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Newman and Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Postman Collection
        run: |
          mkdir -p public
          newman run ./countries_test.json \
            -r cli,htmlextra \
            --reporter-htmlextra-export public/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
