name: Run Multiple Postman Tests

on:
  workflow_dispatch:
    inputs:
      collections:
        description: 'Select Postman collections to run (comma-separated)'
        required: true
        default: countries_test,reqres_test

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      collections: ${{ steps.set-matrix.outputs.collections }}
    steps:
      - name: Prepare Matrix
        id: set-matrix
        run: |
          echo "Input Collections: ${{ github.event.inputs.collections }}"
          collections_json=$(jq -nc --arg cols "${{ github.event.inputs.collections }}" '$cols | split(",")')
          echo "collections=$collections_json" >> $GITHUB_OUTPUT

  run-tests:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        collection: ${{ fromJson(needs.prepare-matrix.outputs.collections) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Newman and Reporter
        run: |
          npm i -g newman newman-reporter-htmlextra

      - name: Run Collection
        run: |
          mkdir -p public
          COLL=${{ matrix.collection }}
          echo "Running collection: $COLL"
          mkdir -p "public/$COLL"
          newman run "collections/${COLL}.json" \
          -r cli,htmlextra \
          --reporter-htmlextra-export "public/$COLL/index.html" --suppress-exit-code

  create-index:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure public folder exists
        run: mkdir -p public
        
      - name: Download all test reports
        uses: actions/download-artifact@v4
        with:
          path: public

      - name: Generate dynamic index.html
        run: |
          mkdir -p public
          {
          echo "<!DOCTYPE html>"
          echo "<html lang=\"en\">"
          echo "<head>"
          echo "  <meta charset=\"UTF-8\">"
          echo "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
          echo "  <title>Test Reports</title>"
          echo "  <style>"
          echo "    body { font-family: Arial, sans-serif; padding: 20px; }"
          echo "    h1 { color: #333; }"
          echo "    ul { list-style-type: none; padding: 0; }"
          echo "    li { margin: 10px 0; }"
          echo "    a { text-decoration: none; color: #007acc; font-size: 18px; }"
          echo "    a:hover { text-decoration: underline; }"
          echo "  </style>"
          echo "</head>"
          echo "<body>"
          echo "  <h1>Test Reports</h1>"
          echo "  <ul>"
      
          found_folder=false
          for d in public/*/ ; do
            if [ -d "$d" ]; then
          folder=$(basename "$d")
          echo "    <li><a href=\"$folder/index.html\">$folder Report</a></li>"
          found_folder=true
            fi
          done

          if [ "$found_folder" = false ]; then
          echo "    <li>No reports found.</li>"
          fi

          echo "  </ul>"
          echo "</body>"
          echo "</html>"
          } > public/index.html


      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: create-index
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
