name: Run Multiple Postman Tests

on:
  workflow_dispatch:
    inputs:
      collections:
        description: 'Select Postman collections to run (comma-separated)'
        required: true
        default: countries_test,reqres_test

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      collections: ${{ steps.set-matrix.outputs.collections }}
    steps:
      - name: Prepare Matrix
        id: set-matrix
        run: |
          echo "Input Collections: ${{ github.event.inputs.collections }}"
          collections_json=$(jq -nc --arg cols "${{ github.event.inputs.collections }}" '$cols | split(",")')
          echo "collections=$collections_json" >> $GITHUB_OUTPUT

  run-tests:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        collection: ${{ fromJson(needs.prepare-matrix.outputs.collections) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Newman and Reporter
        run: |
          npm i -g newman newman-reporter-htmlextra

      - name: Run Collection
        run: |
          mkdir -p public
          COLL=${{ matrix.collection }}
          echo "Running collection: $COLL"
          mkdir -p "public/$COLL"
          newman run "collections/${COLL}.json" \
          -r cli,htmlextra \
          --reporter-htmlextra-export "public/$COLL/index.html" --suppress-exit-code
          
      - name: Debug
        run: ls -R public/${{ matrix.collection }}
          
      - name: Upload Test Report for Collection
        uses: actions/upload-artifact@v4
        with:
          name: github-pages-${{ matrix.collection }}
          path: public/${{ matrix.collection }}

  create-index:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: public

      - name: Generate dynamic index.html
        run: |
          echo "<html><body><h1>Test Reports</h1><ul>" > public/index.html
          for d in public/*/ ; do
            folder=$(basename "$d")
            echo "<li><a href=\"$folder/index.html\">$folder Report</a></li>" >> public/index.html
          done
          echo "</ul></body></html>" >> public/index.html

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: public

  deploy:
    needs: create-index
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
