name: Run Multiple Postman Tests

on:
  workflow_dispatch:
    inputs:
      collections:
        description: 'Select Postman collections to run (comma-separated)'
        required: true
        default: login_tests,api_tests

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      collections: ${{ steps.set-matrix.outputs.collections }}
    steps:
      - name: Prepare Matrix
        id: set-matrix
        run: |
          echo "Input Collections: ${{ github.event.inputs.collections }}"
          collections_json=$(jq -nc --arg cols "${{ github.event.inputs.collections }}" '$cols | split(",")')
          echo "collections=$collections_json" >> $GITHUB_OUTPUT

  run-tests:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        collection: ${{ fromJson(needs.prepare-matrix.outputs.collections) }}
    outputs:
      public-dir: public
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Newman and Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Collection
        run: |
          COLL=${{ matrix.collection }}
          echo "Running collection: $COLL"
          mkdir -p public/$COLL
          newman run "collections/${COLL}.json" \
            -r cli,htmlextra \
            --reporter-htmlextra-export "public/$COLL/index.html" --suppress-exit-code

      - name: Show public folder content
        run: |
          echo "Contents of public/"
          ls -R public

      - name: Upload collection artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.collection }}-report
          path: public/${{ matrix.collection }}

  collect-artifacts:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Download all collection artifacts
        uses: actions/download-artifact@v4
        with:
          path: public

      - name: Generate dynamic index.html
        run: |
            mkdir -p public
            echo '<!DOCTYPE html>
            <html lang="en">
            <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Test Reports</title>
            <style>
            body { font-family: Arial, sans-serif; background: #f4f4f4; margin: 0; padding: 20px; }
            h1 { color: #333; }
            ul { list-style: none; padding: 0; }
            li { background: #fff; margin: 10px 0; padding: 15px; border-radius: 8px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }
            a { text-decoration: none; color: #007acc; font-weight: bold; }
            a:hover { text-decoration: underline; }
            </style>
            </head>
            <body>
            <h1>Test Reports</h1>
            <ul>' > public/index.html

            for d in public/*/ ; do
            folder=$(basename "$d")
            echo "        <li><a href=\"$folder/index.html\">$folder Report</a></li>" >> public/index.html
            done

            echo '      </ul>
            </body>
            </html>' >> public/index.html

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: collect-artifacts
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
